- name: Add epel-release repo
  yum:
    name: epel-release
    state: present

- name: Install nginx
  yum:
    name: nginx
    state: present
    notify:
      - start nginx
- name: Upload the default index.html file
  copy: src=html_files/index.html dest=/usr/share/nginx/www/ mode=0644
